# Generated by Django 4.0.6 on 2022-07-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='entry_num',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
