# Generated by Django 4.0.6 on 2022-07-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='participants',
            field=models.ManyToManyField(to='accounts.student'),
        ),
    ]
