# Generated by Django 4.0.6 on 2022-07-27 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_course_participants_student_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='participants',
            new_name='courses',
        ),
    ]
