# Generated by Django 4.0.6 on 2022-07-27 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_participants_student_courses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grades',
        ),
    ]
